version: '3.3'

services: 
  nodejs:
    container_name: nodejs
    # image_name : 
    build:
      context: ./back-nodejs
      dockerfile: 'docker/Dockerfile'   
    volumes: 
      - './back-nodejs/:/project/'
      - '/project/node_modules'
    command: >
      bash -c "node app.js --host 0.0.0.0 --port 4300"
    ports: 
      - '5000:4300'
    depends_on: 
      - mongo

  

  
  angular:
    container_name: angular
    build:
      context: ./frot-angular
      dockerfile: 'docker/Dockerfile'
    volumes: 
      - './frot-angular:/project'
      - '/project/node_modules'
    command: >
      bash -c "ng serve --host 0.0.0.0 --port 4200"
    ports: 
      - '4200:4200'
    depends_on: 
      - nodejs
      
     
  

  
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    container_name: docker_node_mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: admin
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: password
    #   ME_CONFIG_MONGODB_URL: mongodb:mongodb







